[default]
FLASK_DEBUG="TRUE"

[test]
host="localhost" 
port="3306"
database="snippets_test_a"
user="snippets_test_admin"
SQLALCHEMY_DATABASE_URI="mysql+pymysql://snippets_test_admin:savage@localhost:3306/snippets_test_a"
SECRET_KEY="dev-secret-key-for-testing-only"
